/* eslint-env mocha */
import assert from 'assert';

import { removeHeadersFromCode } from '../../src/modernize/removeAutogeneratedHeader';

describe('removeHeadersFromCode', () => {
  it('works on a simple case', () => {
    let code = `\
/* eslint-disable
    no-unused-vars,
*/
// TODO: This file was created by bulk-decaffeinate.
// Fix any style issues and re-enable lint.
let a = 1;
`;
    assert.equal(removeHeadersFromCode(code), `\
let a = 1;
`);
  });
});
